DROP  DATABASE IF EXISTS  Renting;
CREATE DATABASE Renting;
USE Renting;
##USERS TABLES
DROP  TABLE IF EXISTS USERS;
CREATE TABLE USERS(
	ID INT(4) PRIMARY KEY,
	NAME NVARCHAR(50) NOT NULL,
	PASSWORD  NVARCHAR(50),
	TELEPHONE  NVARCHAR(15),
	USERNAME  NVARCHAR(50),
	ISADMIN NVARCHAR(5)
);
## TYPE TABLE
DROP  TABLE IF EXISTS TYPE;
CREATE TABLE TYPE(
	ID INT(4) PRIMARY KEY,
	NAME NVARCHAR(50) NOT NULL
);

## DISTRICT TABLE
DROP  TABLE IF EXISTS DISTRICT;
CREATE TABLE DISTRICT(
	ID INT(4) PRIMARY KEY,
	NAME NVARCHAR(50) NOT   NULL
);

## STREET TABLE
DROP  TABLE IF EXISTS STREET;
CREATE TABLE STREET(
	ID INT(4) PRIMARY KEY,
	NAME NVARCHAR(50) NOT NULL,
	DISTRICT_ID  INT(4)
);

## HOUSE TABLE
DROP  TABLE IF EXISTS HOUSE;
CREATE TABLE HOUSE(
	ID INT(6) PRIMARY KEY,
	TITLE NVARCHAR(50),
	DESCRIPTION NVARCHAR(2000),
	PRICE INT(6),
	PUBDATE DATE,
	FLOORAGE INT(4),
	CONTACT NVARCHAR(100),
	USER_ID INT(4),
	TYPE_ID INT(4),
	STREET_ID INT(4)
);
ALTER TABLE STREET ADD CONSTRAINT FK_DISTRICT_ID FOREIGN KEY(DISTRICT_ID) REFERENCES DISTRICT(ID);
ALTER TABLE HOUSE ADD CONSTRAINT FK_USER_ID FOREIGN KEY(USER_ID) REFERENCES USERS(ID);
ALTER TABLE HOUSE ADD CONSTRAINT FK_TYPE_ID FOREIGN KEY(TYPE_ID) REFERENCES TYPE(ID);
ALTER TABLE HOUSE ADD CONSTRAINT FK_STREET_ID FOREIGN KEY(STREET_ID) REFERENCES STREET(ID);
SELECT  * FROM USERS;
