##USERS TABLES
CREATE TABLE USERS(
	ID NUMBER(4) PRIMARY KEY,
	NAME NVARCHAR2(50) NOT NULL,
	PASSWORD  NVARCHAR2(50),
	TELEPHONE  NVARCHAR2(15),
	USERNAME  NVARCHAR2(50),
	ISADMIN NVARCHAR2(5)
);
## TYPE TABLE
CREATE TABLE TYPE(
	ID NUMBER(4) PRIMARY KEY,
	NAME NVARCHAR2(50) NOT NULL
);

## DISTRICT TABLE
CREATE TABLE DISTRICT(
	ID NUMBER(4) PRIMARY KEY,
	NAME NVARCHAR2(50) NOt NULL,
);

## STREET TABLE
CREATE TABLE STREET(
	ID NUMBER(4) PRIMARY KEY,
	NAME NVARCHAR2(50) NOT NULL,
	DISTRICT_ID  NUMBER(4)
);

## HOUSE TABLE
CREATE TABLE HOUSE(
	ID NUMBER(6) PRIMARY KEY,
	TITLE NVARCHAR2(50),
	DESCRIPTION NVARCHAR2(2000),
	PRICE NUMBER(6),
	PUBDATE DATE,
	FLOORAGE NUMBER(4),
	CONTACT NVARCHAR2(100),
	USER_ID NUMBER(4),
	TYPE_ID NUMBER(4),
	STREET_ID NUMBER(4)
);
ALTER TABLE STREET ADD CONSTRAINT FK_DISTRICT_ID FOREIGN KEY(DISTRICT_ID) REFERENCES DISTRICT(ID);
ALTER TABLE HOUSE ADD CONSTRAINT FK_USER_ID FOREIGN KEY(USER_ID) REFERENCES USERS(ID);
ALTER TABLE HOUSE ADD CONSTRAINT FK_TYPE_ID FOREIGN KEY(TYPE_ID) REFERENCES TYPE(ID);
ALTER TABLE HOUSE ADD CONSTRAINT FK_STREET_ID FOREIGN KEY() REFERENCES STREET(ID);
