DROP DATABASE IF EXISTS `JBOA`;
CREATE DATABASE `JBOA`;
USE `JBOA`;


## 部门表
DROP TABLE IF EXISTS `SYS_DEPARTMENT`;
CREATE TABLE `SYS_DEPARTMENT`(
	`ID` INT(10)  PRIMARY KEY AUTO_INCREMENT,  ##员工ID
    `NAME` VARCHAR(50) ## 部门名称
)ENGINE=INNODB  AUTO_INCREMENT=1101 DEFAULT CHARSET=UTF8;

## 员工表
DROP TABLE IF EXISTS `SYS_EMPLOYEE`;
CREATE TABLE `SYS_EMPLOYEE`(
	`SN` VARCHAR(50) PRIMARY KEY, ## 用于登录编号
    `POSITION_ID` INT(10), ## 职位外键
    `DEPARTMENT_ID` INT(10), ## 部门外键
    `NAME` VARCHAR(50), ## 真实姓名
    `PASSWORD` VARCHAR(50), ## 密码
    `STATUS` VARCHAR(50) ## 职位状态 在职 离职
)ENGINE=INNODB DEFAULT CHARSET=UTF8;

## 职务表
DROP TABLE IF EXISTS `SYS_POSITION`;
CREATE TABLE `SYS_POSITION`(
	`ID` INT(10)  PRIMARY KEY AUTO_INCREMENT, ##职务ID
    `NAME_CN` VARCHAR(50), ## 职位中文
    `NAME_EN` VARCHAR(50) ## 职位英文
)ENGINE=INNODB  AUTO_INCREMENT=4401 DEFAULT CHARSET=UTF8;

## 报销单审核结果
DROP TABLE IF EXISTS `BIZ_CHECK_RESULT`;
CREATE TABLE `BIZ_CHECK_RESULT`(
	`ID` INT(10)  PRIMARY KEY AUTO_INCREMENT,## 审核ID
    `CLAIM_ID` INT(10),##报销单ID
    `CHECK_TIME` DATE,## 审核时间
    `CHECKER_SN` VARCHAR(50),## 审核人SN编号
    `RESULT` VARCHAR(50),## 审核结果
    `COMM` VARCHAR(500)## 说明
)ENGINE=INNODB  AUTO_INCREMENT=6601 DEFAULT CHARSET=UTF8;

##报销单
DROP TABLE IF EXISTS `BIZ_CLAIM_VOUCHER`;
CREATE TABLE `BIZ_CLAIM_VOUCHER`(
	`ID` INT(10)  PRIMARY KEY AUTO_INCREMENT,
    `NEXT_DEAL_SN` VARCHAR(50), ## 下一步处理人 外键 会不断变化
    `CREATE_SN` VARCHAR(50),## 创建人 
    `CREATE_TIME` DATE,##创建时间
    `MODIFY_TIME` DATE,## 修改时间
    `EVENT` VARCHAR(255), ##事由
    `TOTAL_ACCOUNT` INT(20),## 总金额
    `STATUS` VARCHAR(20)##报销单状态
)ENGINE=INNODB  AUTO_INCREMENT=7701 DEFAULT CHARSET=UTF8;


##报销单明细
DROP TABLE IF EXISTS `BIZ_CLAIM_VOUCHER_DETALL`;
CREATE TABLE `BIZ_CLAIM_VOUCHER_DETALL`(
	`ID` INT(10)  PRIMARY KEY AUTO_INCREMENT,## ID
    `MAIN_ID` INT(10),##外键报销单id
    `ITEM` VARCHAR(50),## 明细的项目
    `ACCOUNT` INT(20),##单项金额
    `DES` VARCHAR(200)##描述
)ENGINE=INNODB  AUTO_INCREMENT=9901 DEFAULT CHARSET=UTF8;

ALTER TABLE `SYS_EMPLOYEE` ADD CONSTRAINT FK_POSITION_ID FOREIGN KEY(`POSITION_ID`) REFERENCES `SYS_POSITION`(`ID`);
ALTER TABLE `SYS_EMPLOYEE` ADD CONSTRAINT FK_DEPART_ID FOREIGN KEY(`DEPARTMENT_ID`) REFERENCES `SYS_DEPARTMENT`(`ID`);
ALTER TABLE `BIZ_CHECK_RESULT` ADD  CONSTRAINT FK_CLAIM_ID FOREIGN KEY(`CLAIM_ID`) REFERENCES `BIZ_CLAIM_VOUCHER`(`ID`);
ALTER TABLE `BIZ_CLAIM_VOUCHER_DETALL` ADD CONSTRAINT FK_MAIN_ID FOREIGN KEY(`MAIN_ID`) REFERENCES `BIZ_CLAIM_VOUCHER`(`ID`);
ALTER TABLE `BIZ_CLAIM_VOUCHER` ADD CONSTRAINT FK_NEXT_SN FOREIGN KEY(`NEXT_DEAL_SN`) REFERENCES `SYS_EMPLOYEE`(`SN`);
ALTER TABLE `BIZ_CLAIM_VOUCHER` ADD CONSTRAINT FK_CREATE_SN FOREIGN KEY (`CREATE_SN`) REFERENCES `SYS_EMPLOYEE`(`SN`);




INSERT INTO `SYS_DEPARTMENT`(`ID`,`NAME`) VALUES(DEFAULT,'员工');
INSERT INTO `SYS_DEPARTMENT`(`ID`,`NAME`) VALUES(DEFAULT,'财务');
INSERT INTO `SYS_DEPARTMENT`(`ID`,`NAME`) VALUES(DEFAULT,'部门经理');
INSERT INTO `SYS_DEPARTMENT`(`ID`,`NAME`) VALUES(DEFAULT,'总经理');


INSERT INTO `SYS_POSITION`(`ID`,`NAME_CN`,`NAME_EN`) VALUES(DEFAULT,'员工','emp');
INSERT INTO `SYS_POSITION`(`ID`,`NAME_CN`,`NAME_EN`) VALUES(DEFAULT,'财务','finance');
INSERT INTO `SYS_POSITION`(`ID`,`NAME_CN`,`NAME_EN`) VALUES(DEFAULT,'部门经理','manager');
INSERT INTO `SYS_POSITION`(`ID`,`NAME_CN`,`NAME_EN`) VALUES(DEFAULT,'总经理','gmanager');

INSERT INTO `SYS_EMPLOYEE`(`SN`,`POSITION_ID`,`DEPARTMENT_ID`,`NAME`,`PASSWORD`,`STATUS`) VALUES('001',4401,1101,'刘雨岑','4QrcOUm6Wau+VuBX8g+IPg==','在职');
INSERT INTO `SYS_EMPLOYEE`(`SN`,`POSITION_ID`,`DEPARTMENT_ID`,`NAME`,`PASSWORD`,`STATUS`) VALUES('002',4402,1102,'陈贻琴','4QrcOUm6Wau+VuBX8g+IPg==','在职');
INSERT INTO `SYS_EMPLOYEE`(`SN`,`POSITION_ID`,`DEPARTMENT_ID`,`NAME`,`PASSWORD`,`STATUS`) VALUES('003',4403,1103,'李富春','4QrcOUm6Wau+VuBX8g+IPg==','在职');
INSERT INTO `SYS_EMPLOYEE`(`SN`,`POSITION_ID`,`DEPARTMENT_ID`,`NAME`,`PASSWORD`,`STATUS`) VALUES('004',4404,1104,'王雨岑','4QrcOUm6Wau+VuBX8g+IPg==','在职');

#INSERT INTO `BIZ_CLAIM_VOUCHER`(`ID`,`NEXT_DEAL_SN`,`CREATE_SN`,`CREATE_TIME`,`MODIFY_TIME`,`EVENT`,`TOTAL_ACCOUNT`,`STATUS`) 
#VALUES(DEFAULT,'002','001','2019-02-13','2019-02-14','',2000,'已提交');
#INSERT INTO `BIZ_CLAIM_VOUCHER`(`ID`,`NEXT_DEAL_SN`,`CREATE_SN`,`CREATE_TIME`,`MODIFY_TIME`,`EVENT`,`TOTAL_ACCOUNT`,`STATUS`) 
#VALUES(DEFAULT,'002','001','2019-02-14','2019-02-15','',8000,'已提交');
#INSERT INTO `BIZ_CLAIM_VOUCHER`(`ID`,`NEXT_DEAL_SN`,`CREATE_SN`,`CREATE_TIME`,`MODIFY_TIME`,`EVENT`,`TOTAL_ACCOUNT`,`STATUS`) 
#VALUES(DEFAULT,'001','001','2019-02-13',NULL,'',3000,'已提交');
#INSERT INTO `BIZ_CLAIM_VOUCHER`(`ID`,`NEXT_DEAL_SN`,`CREATE_SN`,`CREATE_TIME`,`MODIFY_TIME`,`EVENT`,`TOTAL_ACCOUNT`,`STATUS`) 
#VALUES(DEFAULT,'001','001','2019-02-13',NULL,'',4000,'已提交');


#INSERT INTO `BIZ_CHECK_RESULT`(`ID`,`CLAIM_ID`,`CHECK_TIME`,`CHECKER_SN`,`RESULT`,`COMM`) VALUES(DEFAULT,7701,'2019-02-14','004','已审批','王总过生日送礼物');
#INSERT INTO `BIZ_CHECK_RESULT`(`ID`,`CLAIM_ID`,`CHECK_TIME`,`CHECKER_SN`,`RESULT`,`COMM`) VALUES(DEFAULT,7702,'2019-02-15','004','已审批','出差餐饮费用');
#INSERT INTO `BIZ_CHECK_RESULT`(`ID`,`CLAIM_ID`,`CHECK_TIME`,`CHECKER_SN`,`RESULT`,`COMM`) VALUES(DEFAULT,7702,'2019-02-15','004','已审批','机票钱');
#INSERT INTO `BIZ_CHECK_RESULT`(`ID`,`CLAIM_ID`,`CHECK_TIME`,`CHECKER_SN`,`RESULT`,`COMM`) VALUES(DEFAULT,7702,'2019-02-15','004','已审批','工伤住院');


#INSERT INTO `BIZ_CLAIM_VOUCHER_DETALL`(`ID`,`MAIN_ID`,`ITEM`,`ACCOUNT`,`DES`) VALUES(DEFAULT,7701,'礼品费',2000,'送礼');
#INSERT INTO `BIZ_CLAIM_VOUCHER_DETALL`(`ID`,`MAIN_ID`,`ITEM`,`ACCOUNT`,`DES`) VALUES(DEFAULT,7702,'餐饮费',2000,'早中午餐费用');
#INSERT INTO `BIZ_CLAIM_VOUCHER_DETALL`(`ID`,`MAIN_ID`,`ITEM`,`ACCOUNT`,`DES`) VALUES(DEFAULT,7702,'城际交通费',1000,'往返机票');
#INSERT INTO `BIZ_CLAIM_VOUCHER_DETALL`(`ID`,`MAIN_ID`,`ITEM`,`ACCOUNT`,`DES`) VALUES(DEFAULT,7702,'医疗费',3000,'医院住院');
#INSERT INTO `BIZ_CLAIM_VOUCHER_DETALL`(`ID`,`MAIN_ID`,`ITEM`,`ACCOUNT`,`DES`) VALUES(DEFAULT,7703,'出差费',3000,'出差费用');
#INSERT INTO `BIZ_CLAIM_VOUCHER_DETALL`(`ID`,`MAIN_ID`,`ITEM`,`ACCOUNT`,`DES`) VALUES(DEFAULT,7704,'产品费',4000,'产品报销费用');